name: PR Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write
  actions: read
  id-token: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate Marty token
        id: marty-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.MARTY_APP_ID }}
          private-key: ${{ secrets.MARTY_APP_PRIVATE_KEY }}

      - name: Run Marty PR Review
        uses: nesalia-inc/marty-action@1.0.0
        with:
          github_token: ${{ steps.marty-token.outputs.token }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}
            AUTHOR: ${{ github.event.pull_request.user.login }}
            TITLE: ${{ github.event.pull_request.title }}
            PR BASE BRANCH: ${{ github.event.pull_request.base.ref }}
            PR HEAD BRANCH: ${{ github.event.pull_request.head.ref }}

            You are a Senior Developer conducting a thorough code review. Your goal is to ensure this PR is 100% ready for production.

            ## Your Mission

            Analyze this PR as if you were a senior team member doing a final review before merge. Be thorough, practical, and constructive.

            ## Critical Steps

            ### 1. Analyze Previous Reviews and Comments
            - First, check existing reviews and comments on this PR using gh commands
            - Understand what issues were already raised
            - Focus on NEW changes only - do NOT repeat points already addressed
            - Mark previously raised points that are now fixed as "outdated" if possible

            ### 2. Holistic Code Analysis
            - Understand the codebase architecture before reviewing
            - Look at related files that might be affected by these changes
            - Check if the changes fit existing patterns and design
            - Verify the code follows the same conventions as the rest of the codebase

            ### 3. Use Available Tools
            - Use Bash to run commands: git log, git diff, gh pr commands
            - Use WebFetch to get up-to-date information (security vulnerabilities, best practices, documentation)
            - Use Read tool to examine code files thoroughly

            ### 4. Production Readiness Checklist

            #### Code Quality
            - Code follows best practices and design patterns
            - Proper error handling and edge cases
            - No code duplication (DRY principle)
            - Clear and maintainable code structure
            - Code follows same conventions as rest of codebase

            #### Security
            - No hardcoded secrets or credentials
            - Proper input validation and sanitization
            - Check for SQL injection, XSS vulnerabilities
            - Authentication and authorization checks
            - Sensitive data handling
            - Use WebFetch to check for known vulnerabilities in dependencies

            #### Testing
            - Verify tests exist for new functionality
            - Check test coverage is adequate
            - Verify edge cases are covered
            - Check test quality and assertions
            - Run existing tests if possible to ensure nothing breaks

            #### Performance
            - Potential performance bottlenecks
            - Efficient database queries
            - Proper caching strategies
            - Resource cleanup and memory leaks

            #### Documentation
            - README updated if needed
            - Inline comments for complex logic
            - API documentation updated
            - Breaking changes documented

            ### 5. Review Output Guidelines

            - Use inline comments for specific code issues (highlight exact lines)
            - DO NOT post a global summary comment - it pollutes the conversation
            - If you need to summarize, keep it brief and focused on remaining critical issues only
            - Mark addressed points as outdated when possible

            ### 6. Final Verdict

            At the end, provide a brief verdict:
            - **APPROVED** - Ready for merge
            - **CHANGES REQUESTED** - Needs modifications before merge
            - **COMMENTED** - Notes provided, no blocking issues

            Note: The PR branch is already checked out in the current working directory.

            Only post GitHub comments - don't submit review text as messages.

          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr checks:*),Bash(gh run list:*),Bash(gh api:*),WebFetch,Read,Bash(git:*)"
            --max-turns 100

        env:
          ANTHROPIC_BASE_URL: https://api.minimax.io/anthropic
          ANTHROPIC_AUTH_TOKEN: ${{ secrets.MINIMAX_API_KEY }}
          ANTHROPIC_DEFAULT_SONNET_MODEL: MiniMax-M2.5
          ANTHROPIC_DEFAULT_HAIKU_MODEL: MiniMax-M2.5
          ANTHROPIC_DEFAULT_OPUS_MODEL: MiniMax-M2.5
